#!/bin/bash
# 快速创建 go 模板文件, 学习 go 的时候，每次创建 go 文件,加上 package 太麻烦
# go file_name //　创建 or 编辑
# go file_name r // 执行
template_dir=~/.create_template
template_file="$template_dir/template.go"
template_str="package main

import (
    \"fmt\"
)

func main() {

}
"
pre_command="
function GoRunCurrent()
        !go run "%"
endfunction
autocmd filetype go nmap <leader>. :call GoRunCurrent()<Enter>
"

if [ ! -d "$template_dir" ]; then
        mkdir "$template_dir"
fi

if [ ! -f "$template_file" ]; then
        echo "$template_str" > $template_file
fi

if [ ! "$1" ]; then
        echo "文件名参数不能为空"
        exit 0
fi

file_name=$1

if [ ! ${file_name:(-3)} = '.go' ]; then
        file_name=$file_name".go"
fi

if [ -f "$file_name" ]; then
        if [ "r" = "$2" ]; then
                go run $file_name ${*:3}
                exit 0
        fi
        vim $file_name --cmd "$pre_command"
        exit 0
fi

# vim $file_name -c "r $template_file"
vim $file_name --cmd "$pre_command"
