#!/bin/sh

# 通过此脚本可以自动输入 ssh 密码 利用 sshpass 工具 ssh_config 添加 "#Password 你的密码"
host=$1

if [ -z "$host" ]; then
        echo "Usage: $(basename $0) [host] [...params]"
        exit 128
fi

password="$(awk "/^[[:space:]]*[Hh]ost[[:space:]]+$host/ {
        while ( getline a ) {
                if ( a ~ /^[[:space:]]*[Hh]ost[[:space:]]+/ ) {
                        break;
                } else if ( a ~ /^[[:space:]]*#[[:space:]]*[Pp]assword[[:space:]]+/ ) {
                        gsub(/^[[:space:]]*#[[:space:]]*[Pp]assword[[:space:]]+|[[:space:]]*$/, \"\", a);
                        print a;
                        break;
                }
        }
}" ~/.ssh/config)"

ssh_bin="$(which ssh)"

if [ -z "$password" ]; then
        "$ssh_bin" $@
else
        "$(which sshpass)" -p "$password" "$ssh_bin" $@
fi
