#!/bin/sh

# 通过此脚本可以自动输入 ssh 密码 需要 ~/.ssh/config 添加 "#Password 你的密码"
# 支持二次验证自动输入 需要 ~/.ssh/config 添加 "#Secret 你的二次验证secret"
host=$1

if [ -z "$host" ]; then
        echo "Usage: $(basename $0) [host] [...params]"
        exit 128
fi

password="$(awk "/^[[:space:]]*[Hh]ost[[:space:]]+$host/ {
        while ( getline a ) {
                if ( a ~ /^[[:space:]]*[Hh]ost[[:space:]]+/ ) {
                        break;
                } else if ( a ~ /^[[:space:]]*#[[:space:]]*[Pp]assword[[:space:]]+/ ) {
                        gsub(/^[[:space:]]*#[[:space:]]*[Pp]assword[[:space:]]+|[[:space:]]*$/, \"\", a);
                        print a;
                        break;
                }
        }
}" ~/.ssh/config)"
otp_secret="$(awk "/^[[:space:]]*[Hh]ost[[:space:]]+$host/ {
        while ( getline a ) {
                if ( a ~ /^[[:space:]]*[Hh]ost[[:space:]]+/ ) {
                        break;
                } else if ( a ~ /^[[:space:]]*#[[:space:]]*[Ss]ecret[[:space:]]+/ ) {
                        gsub(/^[[:space:]]*#[[:space:]]*[Ss]ecret[[:space:]]+|[[:space:]]*$/, \"\", a);
                        print a;
                        break;
                }
        }
}" ~/.ssh/config)"

ssh_bin="$(which ssh)"

# 由于安全原因，mac电脑上不允许安装 sshpass，注释掉，改用 expect
if [ -z "$password" ]; then
        "$ssh_bin" $@
else
        #"$(which sshpass)" -p "$password" "$ssh_bin" $@
        expect -c "
#spawn ssh $@ \"ls;\"
spawn ssh $@
expect {
    \"*assword\" {set timeout 30; send \"$password\r\";}
    \"yes/no\" {send \"yes\r\"; exp_continue;}
      }
#expect eof\"
expect {
    \"*OTP*\" {set code [exec oathtool --totp -b \"$otp_secret\" ];send \"\$code\r\";}
    }
interact"
fi
